version: '3'

volumes:
  mysql_data:

services:
  graphql:
    container_name: graphql
    build:
      context: $GOPATH/src/github.com/ebalkanski/graphql/
      dockerfile: Dockerfile.dev
    volumes:
      - "$GOPATH/src/github.com/ebalkanski/graphql:/go/src/github.com/ebalkanski/graphql"
    ports:
      - "8080:8080"
    depends_on:
      - grpc

  grpc:
    container_name: grpc
    build:
      context: $GOPATH/src/github.com/ebalkanski/grpc/
      dockerfile: Dockerfile.dev
    volumes:
      - "$GOPATH/src/github.com/ebalkanski/grpc:/go/src/github.com/ebalkanski/grpc"